project_id = "shogmmpqpwkljdlmmcbs"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-support-notification]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = false

[functions.send-custom-email]
verify_jwt = false

[functions.fetch-ga4-data]
verify_jwt = true